build:
  version: "1.0"

accounts:
  message: "Welcome to Delivery accounts related prod APIs config"
  contactDetails:
    name: "Anurag Upadhyay - Product Owner"
    email: "anurag@delivery.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384