build:
  version: "2.0"

accounts:
  message: "Welcome to Delivery accounts related QA APIs config"
  contactDetails:
    name: "Anurag Upadhyay - QA Lead"
    email: "Anurag@delivery.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371