server:
  port: 8080

build:
  version: "3.0"
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true



accounts:
  message: "Welcome to Delivery accounts related local APIs "
  contactDetails:
    name: "Anurag - Developer"
    email: "mavensonair@gmail.com.com"
  onCallSupport:
    - (+91) 98110022
    - (+91) 99110022
