services:
  configserver:
    image: "mavensonair/configserver:a1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "mavensonair/accounts:a1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  delivery:
    driver: "bridge"